// ==============================================
// risePaisa — Calculator Hub Registry
// Catalog of active and upcoming financial calculators
// ==============================================

export const CALCULATOR_REGISTRY = [
  // ── 1. SIP Calculator (ACTIVE) ─────────────────
  {
    id: 'sip',
    title: 'SIP Calculator',
    shortDesc: 'Calculate wealth accumulation and compound maturity returns for Systematic Investment Plans in Nepal.',
    category: 'Investment',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },

  // ── Coming Soon Calculators ────────────────────
  {
    id: 'emi',
    title: 'EMI & Loan Calculator',
    shortDesc: 'Calculate reducing-balance monthly EMIs, total interest, and full repayment schedules for Nepal loans.',
    category: 'Loans',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'swp',
    title: 'SWP Calculator',
    shortDesc: 'Systematic Withdrawal Plan: simulate regular monthly cash flow and project remaining corpus health over time.',
    category: 'Investment',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'home-loan',
    title: 'Home Loan Calculator',
    shortDesc: 'Calculate housing loan installments, LTV health metrics, and long-term interest costs for property in Nepal.',
    category: 'Loans',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'personal-loan',
    title: 'Personal Loan Calculator',
    shortDesc: 'Compute monthly repayment schedules, true borrowing costs, and quick tenure comparisons for personal loans.',
    category: 'Loans',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" y1="8" x2="19" y2="14"/><line x1="22" y1="11" x2="16" y2="11"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'vehicle-loan',
    title: 'Vehicle Loan Calculator',
    shortDesc: 'Calculate down payment, loan ratio, and monthly EMIs for two-wheelers, cars, SUVs, and electric vehicles.',
    category: 'Loans',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'fdrd',
    title: 'Fixed Deposit & RD Calculator',
    shortDesc: 'Calculate FD and RD returns with quarterly/monthly compounding, statutory 5% TDS deduction, and APY yield.',
    category: 'Banking',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21h18M3 10h18M5 10v11M19 10v11M9 10v11M15 10v11M12 2 2 7h20L12 2z"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'tax',
    title: 'Nepal Income Tax Calculator',
    shortDesc: 'Calculate personal income tax for FY 2082/83 across resident individual and married couple progressive slabs.',
    category: 'Tax',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'share',
    title: 'NEPSE Share Calculator',
    shortDesc: 'Complete NEPSE trading suite: Buy Costs, Sell & Profit, Capital Gains Tax, WACC Average Price, and Break-even recovery.',
    category: 'Stocks',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'cagr',
    title: 'CAGR Calculator',
    shortDesc: 'Measure the Compound Annual Growth Rate of your stock, mutual fund, real estate, or business investments.',
    category: 'Investment',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 14 14"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'inflation',
    title: 'Inflation Calculator',
    shortDesc: 'Understand the erosion of purchasing power over time and plan for future price escalation in Nepal.',
    category: 'Planning',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m21.5 2-1.4 1.4A8.24 8.24 0 0 0 2 12a8 8 0 0 0 6 7.7V22h8v-2.3A8 8 0 0 0 22 12c0-1.6-.5-3.2-1.5-4.4L22 6.1z"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'retirement',
    title: 'Retirement & Goal Planner',
    shortDesc: 'Plan long-term retirement corpus needs, inflation escalation, and required monthly SIPs for major life goals.',
    category: 'Planning',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/></svg>`,
    status: 'active',
    badge: 'Popular',
    featured: true,
  },
];
